server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  cache:
    redis:
      time-to-live: 120000
  redis:
    host: 192.168.230.66
    port: 6379
#    password: 123456
  #  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: root
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names:
        a,b
      #主数据来源
      a:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.230.66:3306/reggie?useSSL=false
        username: root
        password: root
      # 从数据源
      b:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.230.77:3306/reggie?useSSL=false
        username: root
        password: root
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: a
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: b
    props:
      sql:
        show: true #开启SQL显示，默认false

mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: /usr/local/imgs/
#  path: d:/imgs/
